services:
  db:
    image: postgres:15
    container_name: cache-system-db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: openjdk:17
    container_name: cache-system-app
    ports:
      - "8081:8081"
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - ../target/cache-system.jar:/app/cache-system.jar
    command: ["java", "-jar", "/app/cache-system.jar"]

volumes:
  pg_data:
